language: objective-c
osx_image: xcode9
install:
    - gem install xcpretty
    - gem install xcpretty-travis-formatter
script:
    - export LC_ALL=en_US.UTF-8
    - xcodebuild clean -project iOSSampleApp.xcodeproj  -scheme iOSSampleApp CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
    - xcodebuild test -project iOSSampleApp.xcodeproj -scheme iOSSampleApp -destination 'platform=iOS Simulator,name=iPhone 6s,OS=11.0' CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
  email:
    on_success: never