language: objective-c
osx_image: xcode9.2
cache:
  directories:
  - Carthage
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --platform iOS --cache-builds  
  - gem install xcpretty
  - gem install xcpretty-travis-formatter
script:
  - export LC_ALL=en_US.UTF-8
  - set -o pipefail && xcodebuild clean -project iOSSampleApp.xcodeproj  -scheme iOSSampleApp CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
  - set -o pipefail && xcodebuild test -project iOSSampleApp.xcodeproj -scheme iOSSampleApp -destination 'platform=iOS Simulator,name=iPhone 6s,OS=11.1' CODE_SIGNING_REQUIRED=NO | xcpretty -f `xcpretty-travis-formatter`
notifications:
  email:
    on_success: never
