name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install needed software
      run: |
        gem install xcpretty 
        gem install bundler:1.16.3
        brew install swiftlint
    - name: Carthage bootstrap
      run: fastlane carthage_bootstrap
    - name: Test
      run: fastlane tests
    - name: Test coverage
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: fastlane test_coverage
